import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ntr = localFont({
  src: "./fonts/NTR/NTR-Regular.ttf",
  variable: "--font-ntr",
  weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Mike",
  description: "Generated by create next app",
  icons: {
    icon: "/favhrt.png?"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ntr.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
